<?php 


//Metabox pour poste post type -> Membres




/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */

function poste_get_meta( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}

function poste_add_meta_box() {
	add_meta_box(
		'poste-poste',
		__( 'Poste', 'poste' ),
		'poste_html',
		'testimonials',
		'normal',
		'default'
	);
}
add_action( 'add_meta_boxes', 'poste_add_meta_box' );

function poste_html( $post) {
	wp_nonce_field( '_poste_nonce', 'poste_nonce' ); ?>

	<p>Selectionnez un poste</p>

	<p>
		<label for="poste_poste"><?php _e( 'poste', 'poste' ); ?></label><br>
		<select name="poste_poste" id="poste_poste">
			<option <?php echo (poste_get_meta( 'poste_poste' ) === 'Ceo Company' ) ? 'selected' : '' ?>>Ceo Company</option>
			<option <?php echo (poste_get_meta( 'poste_poste' ) === 'Sales manager' ) ? 'selected' : '' ?>>Sales manager</option>
			<option <?php echo (poste_get_meta( 'poste_poste' ) === 'Direction Assistants' ) ? 'selected' : '' ?>>Direction Assistants</option>
		</select>
	</p><?php
}

function poste_save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
	if ( ! isset( $_POST['poste_nonce'] ) || ! wp_verify_nonce( $_POST['poste_nonce'], '_poste_nonce' ) ) return;
	if ( ! current_user_can( 'edit_post', $post_id ) ) return;

	if ( isset( $_POST['poste_poste'] ) )
		update_post_meta( $post_id, 'poste_poste', esc_attr( $_POST['poste_poste'] ) );
}
add_action( 'save_post', 'poste_save' );

/*
	Usage: poste_get_meta( 'poste_poste' )
*/
